import React from 'react';
import { Link } from 'react-router-dom';
import TopBar from '../components/TopBar';
import '../styles/legal.css';

export default function PrivacyPolicyPage() {
  return (
    <div className="legal-page">
      <TopBar showConnection={false} />

      <main id="main-content" className="legal-content">
        <Link to="/" className="legal-back-link">
          <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true">
            <path d="M19 12H5m7-7-7 7 7 7"/>
          </svg>
          Back to Home
        </Link>

        <h1>Privacy Policy</h1>
        <p className="legal-meta">Effective date: 1 January 2025 &mdash; Last updated: 1 January 2025</p>

        <p className="legal-intro">
          Open Ride is built on a core principle of privacy by design. This Privacy Policy
          describes how information is handled when you use the Service. By using Open Ride
          you agree to the practices described in this policy.
        </p>

        <div className="legal-section">
          <h2>1. No Data Collection</h2>
          <p>
            Open Ride does <strong>not</strong> collect, transmit, or store any personal data
            on external servers. There is no backend database, no user account system, no
            analytics service, and no telemetry of any kind integrated into the Service.
          </p>
          <p>
            All data generated by your use of the Service (workout history, settings, training
            programmes, device preferences) is stored exclusively in your browser&rsquo;s
            <code style={{margin: '0 0.25rem', padding: '0.1rem 0.35rem', background: 'var(--overlay-md)', borderRadius: '4px', fontSize: '0.85em'}}>localStorage</code>.
            This data never leaves your device unless you explicitly export or share it yourself.
          </p>
        </div>

        <div className="legal-section">
          <h2>2. Information Stored Locally</h2>
          <p>The following data is stored locally in your browser under the keys listed:</p>
          <ul>
            <li><strong>openride_settings</strong> &mdash; your profile data (FTP, maximum heart rate, body weight, unit preferences)</li>
            <li><strong>openride_workout_history</strong> &mdash; summaries of completed rides</li>
            <li><strong>openride_training_program</strong> &mdash; your weekly training schedule</li>
            <li><strong>openride_use_emulator</strong> &mdash; whether the ANT+ emulator is enabled</li>
            <li><strong>openride_was_connected</strong> &mdash; whether a USB dongle was previously connected (used to trigger auto-reconnect)</li>
          </ul>
          <p>
            You can view, export, or delete this data at any time through your browser&rsquo;s
            developer tools or by clearing site data for this origin.
          </p>
        </div>

        <div className="legal-section">
          <h2>3. Hardware Access (WebUSB &amp; Web Bluetooth)</h2>
          <p>
            The Service requests access to USB and Bluetooth hardware devices through the
            WebUSB and Web Bluetooth browser APIs. This access is used solely to communicate
            with ANT+ dongles and BLE fitness devices (trainers, heart rate monitors, power
            meters). No hardware data is transmitted outside your local network or stored
            beyond your current session.
          </p>
          <p>
            Device permissions are managed entirely by your browser and can be revoked at any
            time through your browser&rsquo;s site settings.
          </p>
        </div>

        <div className="legal-section">
          <h2>4. Network Requests</h2>
          <p>
            The Service communicates only with its own local backend server (running on your
            machine, typically at <code style={{margin: '0 0.25rem', padding: '0.1rem 0.35rem', background: 'var(--overlay-md)', borderRadius: '4px', fontSize: '0.85em'}}>localhost:3001</code>)
            to fetch workout files and application status. No requests are made to third-party
            servers, analytics platforms, advertising networks, or content-delivery networks
            as part of normal operation.
          </p>
        </div>

        <div className="legal-section">
          <h2>5. Cookies and Tracking Technologies</h2>
          <p>
            Open Ride does not use cookies, web beacons, pixel tags, fingerprinting techniques,
            or any other tracking technology. The Service does not participate in any advertising
            or cross-site tracking programme.
          </p>
        </div>

        <div className="legal-section">
          <h2>6. Third-Party Services</h2>
          <p>
            Open Ride does not integrate any third-party analytics, crash-reporting, social-media,
            or advertising services. If you access the Service through a hosting provider or
            network that independently logs requests, that provider&rsquo;s own privacy practices
            apply. We have no control over, and accept no responsibility for, such third-party
            data processing.
          </p>
        </div>

        <div className="legal-section">
          <h2>7. Children&rsquo;s Privacy</h2>
          <p>
            The Service is not directed at children under the age of 16. We do not knowingly
            collect personal information from children. If you believe a child has provided
            personal information through the Service, please contact us so we can investigate.
          </p>
        </div>

        <div className="legal-section">
          <h2>8. Your Rights</h2>
          <p>
            Because all data is stored locally on your device and never transmitted to the
            Operator, the Operator holds no personal data about you and therefore has no data
            to provide, correct, or delete on your behalf. To exercise control over your data,
            use your browser&rsquo;s built-in storage management tools to review or clear
            localStorage data for this site at any time.
          </p>
        </div>

        <div className="legal-section">
          <h2>9. Data Security</h2>
          <p>
            Your data security depends on the security of your own device and browser
            environment. We encourage you to keep your operating system and browser up to date
            and to follow general security best practices. The Operator accepts no responsibility
            for unauthorized access to data stored on your local device.
          </p>
        </div>

        <div className="legal-section">
          <h2>10. Changes to This Policy</h2>
          <p>
            We may update this Privacy Policy from time to time. Changes will be reflected by
            updating the &ldquo;Last updated&rdquo; date at the top of this page. Your continued
            use of the Service after any changes constitutes your acceptance of the revised policy.
          </p>
        </div>

        <div className="legal-section">
          <h2>11. Contact</h2>
          <p>
            Questions about this Privacy Policy may be directed to the project&rsquo;s public
            issue tracker at{' '}
            <a href="https://github.com/anthropics/claude-code/issues" rel="noopener noreferrer" target="_blank" style={{color: 'var(--primary-blue)'}}>
              the project repository
            </a>.
          </p>
        </div>
      </main>
    </div>
  );
}
